version: "3.9"

services:
  app:
    image: saas-crm-prod
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saas-crm-prod
    restart: unless-stopped

    ports:
      - "8080:10000" # local only; Render ignores this

    environment:
      PORT: 10000

      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://localhost:8080
      APP_KEY: base64:CHANGE_ME_FOR_LOCAL

      # MongoDB
      DB_CONNECTION: mongodb
      MONGODB_URI: mongodb://mongodb:27017/filament
      MONGODB_DATABASE: filament

      # Redis
      REDIS_CLIENT: phpredis
      REDIS_URL: redis://redis:6379

      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis

      LOG_CHANNEL: stderr

    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - prod

  mongodb:
    image: mongo:7
    container_name: saas-crm-mongodb
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod

  redis:
    image: redis:alpine
    container_name: saas-crm-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod

networks:
  prod:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
